'use client';

import { useState } from 'react';
import { Bot, Loader2, Sparkles } from 'lucide-react';
import {
  Card,
  CardHeader,
  CardTitle,
  CardContent,
  CardDescription,
} from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
} from '@/components/ui/dialog';
import { ScrollArea } from '@/components/ui/scroll-area';
import { generateAnalysisReport } from '@/actions/analysis';
import type { Holding } from '@/types';

type AiAnalystToolProps = {
  holdings: Holding[];
};

export default function AiAnalystTool({ holdings }: AiAnalystToolProps) {
  const [isLoading, setIsLoading] = useState(false);
  const [report, setReport] = useState<string | null>(null);
  const [isDialogOpen, setIsDialogOpen] = useState(false);

  const handleGenerateReport = async () => {
    setIsLoading(true);
    setReport(null);

    const portfolioData = JSON.stringify(holdings, null, 2);
    const result = await generateAnalysisReport({ portfolioData });

    if (result.success && result.data) {
      setReport(result.data.report);
      setIsDialogOpen(true);
    } else {
      // Handle error case, e.g., show a toast notification
      console.error(result.error);
    }

    setIsLoading(false);
  };

  return (
    <Card>
      <CardHeader>
        <CardTitle className="font-headline flex items-center gap-2">
          <Bot className="h-5 w-5" />
          AI Analyst
        </CardTitle>
        <CardDescription>
          Generate a portfolio analysis report with AI.
        </CardDescription>
      </CardHeader>
      <CardContent>
        <div className="space-y-4">
          <p className="text-sm text-muted-foreground">
            Leverage our AI to get a detailed analysis of your current
            portfolio's performance, risk exposure, and potential
            opportunities.
          </p>
          <Button
            onClick={handleGenerateReport}
            disabled={isLoading}
            className="w-full"
          >
            {isLoading ? (
              <Loader2 className="mr-2 h-4 w-4 animate-spin" />
            ) : (
              <Sparkles className="mr-2 h-4 w-4" />
            )}
            Generate Analysis Report
          </Button>
        </div>
      </CardContent>

      <Dialog open={isDialogOpen} onOpenChange={setIsDialogOpen}>
        <DialogContent className="sm:max-w-[625px]">
          <DialogHeader>
            <DialogTitle className="font-headline text-2xl">
              AI Portfolio Analysis
            </DialogTitle>
            <DialogDescription>
              Here is the analysis of your portfolio generated by our AI.
            </DialogDescription>
          </DialogHeader>
          <ScrollArea className="max-h-[60vh] pr-4">
            <div className="prose prose-sm dark:prose-invert max-w-none whitespace-pre-wrap">
              {report}
            </div>
          </ScrollArea>
        </DialogContent>
      </Dialog>
    </Card>
  );
}
